# -*- coding: utf-8 -*-
"""aitask3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NIcgqbGKru2CS3eu07fXKVNenHNLmCAJ
"""

# Source data
electricity_matrix = [
    [550, 650, 750],
    [1800, 2250, 2550],
    [4200, 4600, 4800]
]

# Student ID
student_id = "SU92-BSCSM-F22-061"

# Function to calculate and display cost for slab 1
def costSlab1():
    print("Bill for Slab 1 is")
    for cost in electricity_matrix[0]:
        print(cost, end=" ")
    print()

# Function to calculate and display cost for slab 2
def costSlab2():
    print("Bill for Slab 2 is")
    for cost in electricity_matrix[1]:
        print(cost, end=" ")
    print()

# Function to calculate and display cost for slab 3
def costSlab3():
    print("Bill for Slab 3 is")
    for cost in electricity_matrix[2]:
        print(cost, end=" ")
    print()

# Main menu
while True:
    print(f"My Student ID is {student_id}")
    print("Enter your choice")
    print("Press 1 to display the bill of slab 1 and slab 2.")
    print("Press 2 to display the bill of slab 3.")
    print("Press any other key to exit.")

    choice = input()

    if choice == '1':
        costSlab1()
        costSlab2()
    elif choice == '2':
        costSlab3()
    else:
        print("Program terminated.")
        break

